name: 'Install Module Dependencies'
description: 'Installs the dependencies of a module using the psd1 file'
inputs:
  module-path:  # the full path to the psd1 file
    description: 'the full path to the psd1 file'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/Install-ModuleDependencies.ps1 -ModulePath "${{ inputs.module-path }}"
      shell: pwsh
    - run: |
        $version = ${{ github.action_path }}/Set-VersionNumber.ps1 -ModulePath "${{ inputs.module-path }}" -RevisionNumber ${{ github.run_number }}
        ${{ github.action_path }}/ConvertTo-NuSpec.ps1 -ModulePath "${{ inputs.module-path }}" -Version $version
      shell: pwsh